baseurl: ""
url: "https://secariolabs.com"
twitter_username: SecarioLabs
github_username: secariolabs

defaults:
  - scope:
      path: "pages/home.md"
    values:
      layout: "home"
      permalink: "/"
  - scope:
      path: "pages/about-us.md"
    values:
      layout: "about-us"
      permalink: /about-us/
  - scope:
      path: "pages/services.md"
    values:
      layout: "services"
      permalink: /services/
  - scope:
      path: "pages/contact.md"
    values:
      layout: "contact"
      permalink: /contact/
      type: "plain-page"
  - scope:
      path: "pages/blog.md"
    values:
      layout: "blog"
      permalink: /blog/
      type: "plain-page"
  - scope:
      path: "pages/defence.md"
    values:
      layout: "defence"
      permalink: /defence/
  - scope:
      path: "pages/privacy-policy.md"
    values:
      layout: "plain-page"
      permalink: /privacy-policy/
      type: "plain-page"
  - scope:
      path: "pages/terms-and-conditions.md"
    values:
      layout: "plain-page"
      permalink: /terms-and-conditions/
      type: "plain-page"
  - scope:
      path: "pages/modern-slavery-policy.md"
    values:
      layout: "plain-page"
      permalink: /modern-slavery-policy/
      type: "plain-page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: :slug/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  # - jekyll-seo-tag
  # - jekyll-minifier

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  tags:
    layouts:
      - "autopage_tags.html"
    title: "Posts tagged as :tag"
    permalink: /tag/:tag/
    silent: false
    slugify:
      mode: "default"
      case: false
  categories:
    enabled: false
  collections:
    enabled: false

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.txt
  - README.md
  - gulpfile.js
