name: Check British English

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install spell checker
        run: pip install codespell

      - name: Run spell check for British English
        run: |
          codespell --ignore-words-list "colorize,localize" --quiet-level=2 \
            --skip=".git,*.png,*.jpg,*.jpeg,*.svg,*.ico,*.woff,*.woff2,*.eot,*.ttf,*.otf,_site/" \
            --check-hidden --write-changes \
            --ignore-words=".codespell_ignore" \
            pages/ _posts/ ./

      - name: Fail if American English words are found
        run: |
          if git diff --exit-code; then
            echo "✅ No American English words found."
          else
            echo "❌ American English detected! Please use British spelling."
            exit 1
          fi
